#ifndef __TRADEMGEN_CMD_DEMANDMANAGER_HPP
#define __TRADEMGEN_CMD_DEMANDMANAGER_HPP

// //////////////////////////////////////////////////////////////////////
// Import section
// //////////////////////////////////////////////////////////////////////
// StdAir
#include <stdair/STDAIR_Types.hpp>
#include <stdair/bom/DemandStreamTypes.hpp>
#include <stdair/bom/BookingRequestTypes.hpp>
#include <stdair/command/CmdAbstract.hpp>
// Trademgen
#include <trademgen/TRADEMGEN_Types.hpp>

// Forward declarations
namespace stdair {
  class BomRoot;
  class DemandCharacteristics;
  class DemandDistribution;
}

namespace TRADEMGEN {

  /** Utility class for Demand and DemandStream objects. */
  class DemandManager : public stdair::CmdAbstract {
  public:
    // //////// Business methodes //////////
    /** Add a demand stream into the context. */
    static void addDemandStream (stdair::DemandStreamList_T&,
                                 const stdair::DemandStreamKey_T&,
                                 const stdair::DemandCharacteristics&,
                                 const stdair::DemandDistribution&,
                                 const stdair::RandomSeed_T&,
                                 const stdair::RandomSeed_T&,
                                 const stdair::RandomSeed_T&);
    
    /** Get the total number of requests to be generated by the demand
        stream which corresponds to the given key. */
    static const stdair::NbOfRequests_T&
    getTotalNumberOfRequestsToBeGenerated (const stdair::DemandStreamList_T&,
                                           const stdair::DemandStreamKey_T&);

    /** Check whether enough requests have already been generated for
        the demand stream which corresponds to the given key. */
    static const bool
    stillHavingRequestsToBeGenerated (const stdair::DemandStreamList_T&,
                                      const stdair::DemandStreamKey_T&);

    /** Generate a request with the demand stream which corresponds to
        the given key. */
    static stdair::BookingRequestPtr_T
    generateNextRequest (stdair::DemandStreamList_T&,
                         const stdair::DemandStreamKey_T&);
  };

}
#endif // __TRADEMGEN_CMD_DEMANDMANAGER_HPP
