#!/bin/sh

# Log file generated by TraDemGen 
LOG_FILE="trademgen.log"

#
LOG_FILE_OPTION="NO"
for opt_elem in $@
do
  if [ "${opt_elem}" = "-h" -o "${opt_elem}" = "-H" -o "${opt_elem}" = "--h" -o "${opt_elem}" = "--help" ]
  then
    echo ""
    echo " This script extracts booking request data from the log file generated by the trademgen batch."
    echo " "
    echo "Usage:"
    echo "    \$0 [-l/--logfile <logfile>]"
    echo ""
    exit 0
  fi
  if [ "${LOG_FILE_OPTION}" ="YES" -o "${opt_elem}" = "-l" -o "${opt_elem}" = "--logfile" ]
  then
      if [ "${LOG_FILE_OPTION}" = "NO" ]
      then
	  LOG_FILE="${opt_elem}"
	  LOG_FILE_OPTION="YES"
      else
	  LOG_FILE_OPTION="NO"
      fi
  fi
done

grep -n "Poped" ${LOG_FILE} | \
 sed -e "s/^\([0-9]\+\).*\(20[0-9]\+-[A-Z][a-z]\+-[0-9]\+\).*\ \([A-Z]\+-[A-Z]\+\)\ .*\(20[0-9]\+-[A-Z][a-z]\+-[0-9]\+\).*$/\1,\t\2, \3, \4/" | sort -k3
